/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import MecanicasJogo.*;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class TelaLogin extends javax.swing.JFrame {

    private JogoGUI jogo;
    private Jogadores jogador1,jogador2;
    private Random random = new Random();
    private int randomNum;
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        this.jogo = new JogoGUI();
        this.jogador1 = new Jogadores("",20,15,jogo.getListaCartas1(),null);
        this.jogador2 = new Jogadores("",20,15,jogo.getListaCartas2(),null);
        initComponents();
    }
    
    public Jogadores qualJogadorComeca(){
        randomNum = random.nextInt(2);
        
        if(randomNum == 0){
            JOptionPane.showMessageDialog(this,this.jogador1.getNomeJogador()+" começa o jogo(de cima)!");
            return jogador1;
        }
        else{
            JOptionPane.showMessageDialog(this,this.jogador2.getNomeJogador()+" começa o jogo(de baixo)!");
            return jogador2;
        }
    }
    
    public Jogadores getJogador1(){
        return jogador1;
    }
    public Jogadores getJogador2(){
        return jogador2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        nomeJ1 = new javax.swing.JLabel();
        txtNomeJ1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        nomeJ2 = new javax.swing.JLabel();
        txtNomeJ2 = new javax.swing.JTextField();
        btnComecoJogo = new javax.swing.JButton();
        texto1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(153, 0, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(560, 360));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        nomeJ1.setBackground(new java.awt.Color(51, 204, 255));
        nomeJ1.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        nomeJ1.setText("Nome Jogador 1");

        txtNomeJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeJ1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(nomeJ1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeJ1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(nomeJ1)
                .addComponent(txtNomeJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        nomeJ2.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        nomeJ2.setText("Nome Jogador 2");

        txtNomeJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeJ2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(nomeJ2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeJ2, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(nomeJ2)
                .addComponent(txtNomeJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnComecoJogo.setBackground(new java.awt.Color(51, 255, 0));
        btnComecoJogo.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        btnComecoJogo.setText("Jogar");
        btnComecoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComecoJogoActionPerformed(evt);
            }
        });

        texto1.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        texto1.setText("Selecione os nomes dos duelistas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(texto1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(btnComecoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(texto1)
                .addGap(52, 52, 52)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnComecoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeJ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeJ1ActionPerformed

    private void txtNomeJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeJ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeJ2ActionPerformed

    private void btnComecoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComecoJogoActionPerformed
        // TODO add your handling code here:
        if(txtNomeJ1.getText() == "" || txtNomeJ2.getText() == ""){
            JOptionPane.showMessageDialog(this,"Por favor, complete ambos os campos dos jogadores.");
        }
        else{
            jogador1.setNomeJogador(txtNomeJ1.getText());
            jogador2.setNomeJogador(txtNomeJ2.getText());
            
            TelaCombateGUI tela2 = new TelaCombateGUI(jogador1,jogador2);
            
            if(this.qualJogadorComeca() == jogador1){
                tela2.desabilitaMao(tela2.getBtn1CartaMao2(), tela2.getBtn2CartaMao2(), tela2.getBtn3CartaMao2(), tela2.getBtn4CartaMao2(), tela2.getBtn5CartaMao2(), tela2.getBtn1CampoDeBatalha2(), tela2.getBtn1CampoDeBatalha2(), tela2.getBtn1CampoDeBatalha2());
            }
            else{
                tela2.desabilitaMao(tela2.getBtn1CartaMao1(), tela2.getBtn2CartaMao1(), tela2.getBtn3CartaMao1(), tela2.getBtn4CartaMao1(), tela2.getBtn5CartaMao1(), tela2.getBtn1CampoDeBatalha1(), tela2.getBtn1CampoDeBatalha1(), tela2.getBtn1CampoDeBatalha1());
            }
            
            this.dispose();
            tela2.setVisible(true);
        }
    }//GEN-LAST:event_btnComecoJogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnComecoJogo;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel3;
    javax.swing.JLabel nomeJ1;
    javax.swing.JLabel nomeJ2;
    javax.swing.JLabel texto1;
    javax.swing.JTextField txtNomeJ1;
    javax.swing.JTextField txtNomeJ2;
    // End of variables declaration//GEN-END:variables
}
