/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import MecanicasJogo.*;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class TelaEscolhaDuelo extends javax.swing.JFrame {

    private JogoGUI jogo;
    private Jogadores jogadorAtacado;
    private TelaCombateGUI telaCombate;
    
    /**
     * Creates new form TelaEscolhaDuelo
     */
    public TelaEscolhaDuelo(Jogadores jogadorAtacado, JogoGUI jogo, TelaCombateGUI telaCombate) {
        this.jogo = jogo;
        this.jogadorAtacado = jogadorAtacado;
        this.telaCombate = telaCombate;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpEscolhaCartaDuelo = new javax.swing.JPanel();
        escolhaDuelo = new javax.swing.JLabel();
        jbCarta2 = new javax.swing.JButton();
        jbCarta1 = new javax.swing.JButton();
        jbCarta3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));

        jpEscolhaCartaDuelo.setBackground(new java.awt.Color(153, 51, 0));

        escolhaDuelo.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        escolhaDuelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        escolhaDuelo.setText("Escolha qual carta Deseja Atacar");

        jbCarta2.setBackground(new java.awt.Color(153, 102, 0));
        jbCarta2.setFont(new java.awt.Font("Castellar", 0, 12)); // NOI18N
        jbCarta2.setText("Carta2");
        jbCarta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta2ActionPerformed(evt);
            }
        });

        jbCarta1.setBackground(new java.awt.Color(153, 102, 0));
        jbCarta1.setFont(new java.awt.Font("Castellar", 0, 12)); // NOI18N
        jbCarta1.setText("Carta1");
        jbCarta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta1ActionPerformed(evt);
            }
        });

        jbCarta3.setBackground(new java.awt.Color(153, 102, 0));
        jbCarta3.setFont(new java.awt.Font("Castellar", 0, 12)); // NOI18N
        jbCarta3.setText("Carta3");
        jbCarta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCarta3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpEscolhaCartaDueloLayout = new javax.swing.GroupLayout(jpEscolhaCartaDuelo);
        jpEscolhaCartaDuelo.setLayout(jpEscolhaCartaDueloLayout);
        jpEscolhaCartaDueloLayout.setHorizontalGroup(
            jpEscolhaCartaDueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEscolhaCartaDueloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escolhaDuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpEscolhaCartaDueloLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jbCarta2)
                .addGap(18, 18, 18)
                .addComponent(jbCarta1)
                .addGap(18, 18, 18)
                .addComponent(jbCarta3))
        );
        jpEscolhaCartaDueloLayout.setVerticalGroup(
            jpEscolhaCartaDueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEscolhaCartaDueloLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(escolhaDuelo)
                .addGap(26, 26, 26)
                .addGroup(jpEscolhaCartaDueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCarta3)
                    .addComponent(jbCarta1)
                    .addComponent(jbCarta2))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEscolhaCartaDuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEscolhaCartaDuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCarta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta1ActionPerformed
        if(jogadorAtacado == telaCombate.getJogador1()){    
           
            if(telaCombate.getCarta1Campo1() != null){
                jogadorAtacado.setCarta(telaCombate.getCarta1Campo1());
                telaCombate.quemRecebeAtaqueNoCampo(jogadorAtacado);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this,this.jogadorAtacado.getNomeJogador()+" não possui nenhuma carta nesse espaço!");
            }
        }
        else if(jogadorAtacado == telaCombate.getJogador2()){
            
            if(telaCombate.getCarta1Campo2() != null){
                jogadorAtacado.setCarta(telaCombate.getCarta1Campo2());
                telaCombate.quemRecebeAtaqueNoCampo(jogadorAtacado);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this,this.jogadorAtacado.getNomeJogador()+" não possui nenhuma carta nesse espaço!");
            }
        }
    }//GEN-LAST:event_jbCarta1ActionPerformed

    private void jbCarta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta2ActionPerformed
        if(jogadorAtacado == telaCombate.getJogador1()){    
            
            if(telaCombate.getCarta2Campo1() != null){
                jogadorAtacado.setCarta(telaCombate.getCarta2Campo1());
                telaCombate.quemRecebeAtaqueNoCampo(jogadorAtacado);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this,this.jogadorAtacado.getNomeJogador()+" não possui nenhuma carta nesse espaço!");
            }
        }
        else if(jogadorAtacado == telaCombate.getJogador2()){
            if(telaCombate.getCarta2Campo2() != null){
                jogadorAtacado.setCarta(telaCombate.getCarta2Campo2());
                telaCombate.quemRecebeAtaqueNoCampo(jogadorAtacado);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this,this.jogadorAtacado.getNomeJogador()+" não possui nenhuma carta nesse espaço!");
            }
        }
    }//GEN-LAST:event_jbCarta2ActionPerformed

    private void jbCarta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCarta3ActionPerformed
        if(jogadorAtacado == telaCombate.getJogador1()){    
            
            if(telaCombate.getCarta3Campo1() != null){
                jogadorAtacado.setCarta(telaCombate.getCarta3Campo1());
                telaCombate.quemRecebeAtaqueNoCampo(jogadorAtacado);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this,this.jogadorAtacado.getNomeJogador()+" não possui nenhuma carta nesse espaço!");
            }
        }
        else if(jogadorAtacado == telaCombate.getJogador2()){
            
            if(telaCombate.getCarta3Campo2() != null){
                jogadorAtacado.setCarta(telaCombate.getCarta3Campo2());
                telaCombate.quemRecebeAtaqueNoCampo(jogadorAtacado);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this,this.jogadorAtacado.getNomeJogador()+" não possui nenhuma carta nesse espaço!");
            }
        }
    }//GEN-LAST:event_jbCarta3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaDuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaDuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaDuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEscolhaDuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaEscolhaDuelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel escolhaDuelo;
    private javax.swing.JButton jbCarta1;
    private javax.swing.JButton jbCarta2;
    private javax.swing.JButton jbCarta3;
    private javax.swing.JPanel jpEscolhaCartaDuelo;
    // End of variables declaration//GEN-END:variables
}
